version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "I am on main"
            - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: python3 main-test.py
  approval:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - Hold-for-Approval:
          type: approval
          requires:
            - build
            - test
      - approval:
          requires:
            - Hold-for-Approval